# 1. Etapa de compilación
FROM openjdk:21-jdk-slim AS build


WORKDIR /app

COPY . .

RUN ./mvnw clean package -DskipTests

# 2. Etapa de ejecución

FROM openjdk:21-slim


WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]
